### ISSUE TITLE
Docs for iiqtools_cluster_backup need to account for posix permission on key file

### ISSUE THREAD

**Issue by willnx** [willnx/iiqtools#29]
![doh](https://13495-presscdn-0-63-pagely.netdna-ssl.com/wp-content/uploads/2016/04/homer-computer-doh1.jpg)

```
[iiq_backup@foo~]$ iiqtools_cluster_backup --show-clusters
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/bin/iiqtools_cluster_backup", line 7, in <module>
    from iiqtools.iiqtools_cluster_backup import main
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/iiqtools/iiqtools_cluster_backup.py", line 12, in <module>
    from iiq_data_export.api_connection import iiq_api
  File "/usr/share/isilon/lib/python2.7/site-packages/iiq_data_export/__init__.py", line 32, in <module>
    import command_config
  File "/usr/share/isilon/lib/python2.7/site-packages/iiq_data_export/command_config.py", line 45, in <module>
    import utils
  File "/usr/share/isilon/lib/python2.7/site-packages/iiq_data_export/utils.py", line 19, in <module>
    from api_connection import iiq_api
  File "/usr/share/isilon/lib/python2.7/site-packages/iiq_data_export/api_connection/iiq_api.py", line 14, in <module>
    import iiq_api_connection
  File "/usr/share/isilon/lib/python2.7/site-packages/iiq_data_export/api_connection/iiq_api_connection.py", line 17, in <module>
    from insightiq.lib.api_connection.api import APIConnectionError
  File "/usr/share/isilon/lib/python2.7/site-packages/insightiq/lib/api_connection/api.py", line 15, in <module>
    from insightiq.lib.utils import resolver, cipher
  File "/usr/share/isilon/lib/python2.7/site-packages/insightiq/lib/utils/cipher.py", line 61, in <module>
    SECRET_KEY = read_secret_key()
  File "/usr/share/isilon/lib/python2.7/site-packages/insightiq/lib/utils/cipher.py", line 35, in read_secret_key
    with open(path, 'r') as f:
IOError: [Errno 13] Permission denied: '/etc/isilon/secret_key'
```

**Comment by willnx** [comment]
Fixed via https://github.com/willnx/iiqtools/pull/31
